### ISSUE TITLE
no `readFile` function has been passed in as a plugin option

### ISSUE THREAD

**Issue by codedependant** [interactivethings/postcss-includes#1]
Hey there

This package is exactly what I've been looking for to work with in conjuction with css-modules. Thank you for writing it!

However I seem to be getting the error `no 'readFile' function has been passed in as a plugin option` when including a class from another file.

Any ideas why this would be the case?

**Comment by grossbart** [comment]
Hey @codedependant, glad you like it!

Even though I do use this plugin in real projects, I didn't really have the time to polish it and so did not yet document the `readFile` function. For now I can attach you an example of how I'm using it as part of a Webpack config. The reason the `readFile` function needs to be defined like this is so that we can load files referenced by an `includes: ` statement using Webpack's load paths. This example also shows that the `postcss` config option can be a function that returns an array of plugins to use.

    …,
    postcss: function () {
      // The context of this function is the same provided to postcss-loader
      // see: http://webpack.github.io/docs/loaders.html
      var loaderContext = this
      function readFile (filepath) {
        return new Promise(function (resolve, reject) {
          loaderContext.resolve(loaderContext.context, filepath, function (moduleError, realpath) {
            if (moduleError) return reject(moduleError)
            fs.readFile(realpath, 'utf8', function (readFileError, contents) {
              readFileError ? reject(readFileError) : resolve(contents)
            })
          })
        })
      }

      return [
        cssincludes({readFile: readFile}),
        cssnested,
        autoprefixer({
          browsers: [
            '>1%',
            'last 4 versions',
            'Firefox ESR',
            'not ie < 9' // React doesn't support IE8 anyway
          ]
        })
      ]
    },
    …

**Comment by codedependant** [comment]
Thanks for response and snippet @naehrstoff, really appreciate it! Works like a charm.

Unfortunately I ran into a bunch of other issues when trying to use postcss-includes within react-starter-kit, so I'm forced to abandon that approach for now due to time constraints. But I hope to come back to it at some point down the line.

Anyway thanks again for the response and for releasing this. Cheers!
